function = "stderr"
description = "Write a formatted value to standard error"
source = "stderr.rs"
docs = "stderr.md"
impure = true

[[input]]
name = "value"

[[input]]
name = "format"
type = "string"
