[package]
name = "flowsamples"
version = "0.60.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
readme = "README.md"
description = "A set of sample 'flow' programs"
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/flow/samples/README.md"
homepage = "https://andrewdavidmackenzie.github.io/flow/"
repository = "https://github.com/andrewdavidmackenzie/flow/"
edition = "2021"

build = "build.rs"

[badges]
maintenance = { status = "actively-developed" }

[[bin]]
name = "flowsamples"
path = "main.rs"

[dev-dependencies]
serial_test = "0.8.0"
