function = "file_write"
description = "Write content to a file"
source = "file_write.rs"
docs = "file_write.md"
impure = true

[[input]]
name = "filename"
type = "string"

[[input]]
name = "bytes"
type = "array/number"