function = "readline"
description = "Read a line of text with an optional prompt"
source = "readline.rs"
docs = "readline.md"
impure = true

[[input]]
name = "prompt"
type = "string"

[[output]]
name = "string"
type = "string"

[[output]]
name = "json"