function = "stdout"
description = "Write a formatted value to standard output"
source = "stdout.rs"
docs = "stdout.md"
impure = true

[[input]]
name = "value"

[[input]]
name = "format"
type = "string"
