function = "duplicate_rows"
source = "duplicate_rows.rs"
docs = "duplicate_rows.md"
type = "rust"

[[input]]
type = "array/array/number" # Input matrix

[[input]]
name = "factor" # - duplication factor
type = "number"

[[output]]
type = "array/array/number" # - matrix with duplicated rows