function = "histogram"
description = "Render an array of numbers as a bar chart image (Nx128 grayscale, width matches number of bins)"
source = "histogram.rs"
docs = "histogram.md"
type = "rust"

[[input]]
name = "bins"
type = "array/number"

[[output]]
name = "grid" # 2D grayscale grid (black bars on white background)
type = "array/array/number"
