[package]
name = "reshape"
version = "0.1.0"
edition = "2021"
[lib]
name = "reshape"
crate-type = ["cdylib"]
path = "reshape.rs"
[profile.release]
panic = 'abort'
[dependencies]
flowcore = {path = "../../../../flowcore", version = "0"}
flowmacro = {path = "../../../../flowmacro", version = "0"}
serde_json = { version = "1.0", default-features = false }
[workspace]
exclude = ["../../..", ".."]
