function = "reshape"
description = "Reshape a flat array into a 2D grid"
source = "reshape.rs"
docs = "reshape.md"
type = "rust"
[[input]]
name = "pixels"
type = "array/number"
[[input]]
name = "width"
type = "number"
[[output]]
name = "grid"
type = "array/array/number"
