flow = "arrays"
docs = "DESCRIPTION.md"

[metadata]
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[[process]]
source = "lib://flowstdlib/math/sequence"
input.start = {once =  1}
input.limit = {once =  20}
input.step = {once =  1}

[[connection]]
from = "sequence/sequence"
to = "accumulator/values"

[[process]]
alias = "accumulator"
source = "lib://flowstdlib/data/accumulate"
input.partial = {once =  []}
input.chunk_size = {always =  4}

[[connection]]
from = "accumulator/partial"
to = "accumulator/partial"

[[connection]]
from = "accumulator/chunk"
to = "add/i1"

[[process]]
source = "lib://flowstdlib/math/add"
input.i2 = {always =  1}

[[connection]]
from = "add"
to = "stdout"

[[process]]
source = "context://stdio/stdout"