app: build
	@echo "------------ Starting 'ide-native' as electron app ----------------"
	@npm start

build:
	@echo "\n------- Started building ide-native -----------"
	@echo "Not implemented yet"
	@echo "--------- Finished building ide-native -----------"
	@cargo build

package:
	@echo "\n------- Started  packaging ide-native -----------"
	@echo "Not implemented yet"
	@echo "--------- Finished packaging ide-native -----------"

clean:
	@cargo clean
	@rm -rf pkg target Cargo.lock package-lock.json node_modules