flow = "args"
docs = "DESCRIPTION.md"

[[process]]
source = "context://args/get"

[[process]]
source = "context://stdio/stdout"

[[connection]]
name = "print-flow-name"
from = "get/json/2"
to = "stdout"