[book]
title = "The 'flow' book"
authors = ["Andrew Mackenzie"]
description = "What is 'flow' and how to use it?"
multilingual = false
src = "."

[build]
build-dir = "target"
create-missing = false
use-default-preprocessors = false

[output.html]
[preprocessor.links]

[output.linkcheck]