[workspace]
members = ["flowc", "flowstdlib", "flowrlib", "flowr", "flowrex", "flowcore", "flowmacro", "flowsamples",
    "flowide"]
default-members = ["flowc", "flowstdlib", "flowrlib", "flowr", "flowrex", "flowcore", "flowmacro",
    "flowsamples", "flowide"]
resolver = "2"

[workspace.package]
version = "0.95.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
license = "MIT"
license-file = "LICENSE"
documentation = "https://github.com/andrewdavidmackenzie/flow/README.md"
homepage = "http://andrewdavidmackenzie.github.io/flow/"
repository = "https://github.com/andrewdavidmackenzie/flow/"
readme = "README.md"
edition = "2021"

[profile.dev]
split-debuginfo = "unpacked"

# Config for "cargo release" to work with a Virtual Workspace with Unified Version number across packages
[workspace.metadata.release]
shared-version = true
tag-name = "v{{version}}"

[workspace.metadata.dist]
ci = ["github"]
installers = ["shell"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin"]

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"

