codecov:
  token: 19030176-6eb5-440c-9948-e9eb6a6a2e20

coverage:
  round: down
  precision: 0
  status:
    project:
      default:
        target: auto
        threshold: 20%
    patch:
      default:
        target: auto
        threshold: 20%