[package]
name = "mandlebrot"
description = "A standalone rust project for generating a Mandlebrot PNG image"
version = "0.11.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2021"

[[bin]]
name="mandlebrot"
path = "main.rs"

[dependencies]
flowcore = {path = "../../../../flowcore", version = "0"}
flowmacro = {path = "../../../../flowmacro", version = "0"}
serde_json = "1.0"
num = "0.4.0"
image = "0.23.12"
rayon = "*"
tempfile = "3"
dir-diff = "*"

[workspace]
exclude = ["../../.."]