flow = "reverse-echo"

[[process]]
alias = "reverse"
source = "reverse/reverse"

[[connection]]
name = "normal"
from = "flowruntime/stdio/readline/string"
to = "reverse"

[[connection]]
name = "reversed"
from = "reverse/reversed"
to = "flowruntime/stdio/stdout"