function = "join"
source = "join.rs"
docs = "join.md"
type = "rust"

[[input]]
name = "data" # - the data we wish to control the flow of

[[input]]
name = "control" # - a second value we wait on

[[output]]