flow = "parse_args"

[[output]]
name = "filename"
type = "string"

[[output]]
name = "size"
type = "array/number"

[[output]]
name = "bounds"
type = "array/array/number"

# Args
[[process]]
alias = "args"
source = "context://args/get"

############# filename
[[connection]]
from = "args/string/1"
to = "output/filename"

############## size
[[connection]]
from = "args/json/2"
to = "output/size"

[[connection]]
from = "args/json/3"
to = "output/bounds"