function = "compose_matrix"
source = "compose_matrix.rs"
docs = "compose_matrix.md"
type = "rust"

[[input]]
name = "element"
type = "number" # matrix elements

[[input]]
name = "element_indexes"
type = "array/number"

[[input]]
name = "partial"
type = "array/array/number"

[[output]]
name = "matrix"
type = "array/array/number"

[[output]]
name = "partial"
type = "array/array/number"