flow = "matrix_mult"
docs = "DESCRIPTION.md"

[[process]]
source = "context://stdio/readline"
input.prompt = { always =  "" }

[[process]]
alias = "select_0"
source = "lib://flowstdlib/control/index_f"
input.select_index = { always = 0 }

[[connection]]
from = "readline/json"
to = "select_0/value"

[[process]]
alias = "select_1"
source = "lib://flowstdlib/control/index_f"
input.select_index = { always = 1 }

[[connection]]
from = "readline/json"
to = "select_1/value"

[[process]]
source = "multiply"

[[connection]]
from = "select_0/selected_value"
to = "multiply/a"

[[connection]]
from = "select_1/selected_value"
to = "multiply/b"

[[process]]
source = "context://stdio/stdout"

[[connection]]
from = "multiply/product"
to = "stdout"