function = "multiply"
source = "multiply.rs"
docs = "multiply.md"
type = "rust"

[[input]]
name = "i1" # - one number, of type `Number`
type = "number"

[[input]]
name = "i2" # - the other number, of type `Number`
type = "number"

[[output]]
type = "number" # - the multiplication of i1 and i2, of type `Number`