flow = "candidates"

[[input]]
name = "limit"
type = "number"

[[output]]
name = "candidates"
type = "array/number"

####### Generate sequence of candidate numbers from 2..limit
[[process]]
source = "lib://flowstdlib/math/sequence"
input.start = {once = 2}
input.step = {once = 1}

[[connection]]
from = "input/limit"
to = "sequence/limit"

####### Compute chunk_size = limit - 1 (since we start at 2, not 1)
[[process]]
alias = "chunk-size"
source = "lib://flowstdlib/math/subtract"
input.i2 = {once = 1}

[[connection]]
from = "input/limit"
to = "chunk-size/i1"

####### Accumulate numbers into an array
[[process]]
source = "lib://flowstdlib/data/accumulate"
input.partial = {once = []}

[[connection]]
from = "sequence/number"
to = "accumulate/values"

[[connection]]
from = "chunk-size"
to = "accumulate/chunk_size"

[[connection]] # loop-back
from = "accumulate/chunk_size"
to = "accumulate/chunk_size"

[[connection]] # loop-back
from = "accumulate/partial"
to = "accumulate/partial"

# Output the gathered array
[[connection]]
from = "accumulate/chunk"
to = "output/candidates"
