function = "select"
source = "select.rs"
docs = "select.md"
type = "rust"

[[input]]
name = "i1"

[[input]]
name = "i2"

[[input]]
name = "control" # - a boolean value to selection of inputs passed to outputs
type = "boolean"

[[output]]
name = "select_i1" # if `control` is true `i1` is selected for this output else `i2` is selected

[[output]]
name = "select_i2" # if `control` is true `i2` is selected for this output else `i1` is selected