function = "reverse"
source = "reverse.rs"
docs = "reverse.md"
type = "rust"

[[input]]
type = "string" # The String to reverse

[[output]]
name = "reversed" # - The input string reversed
type = "string"