flow = "my-first-flow"
docs = "DESCRIPTION.md"

[metadata]
version = "1.0.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[[process]]
source = "lib://flowstdlib/math/add"
input.i1 = { once =  0 }
input.i2 = { once =  1 }

[[connection]]
from = "add"
to = "add/i2"

[[connection]]
from = "add"
to = "stdout"

# Loop back the input value #2 from this calculation, to be the input to input #1 on the next iteration
[[connection]]
from = "add/i2"
to = "add/i1"

[[process]]
source = "context://stdio/stdout"