flow = "my-first-flow"
docs = "DESCRIPTION.md"

[metadata]
version = "1.0.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]

[[process]]
source = "lib://flowstdlib/math/add"
x = 50
y = 50
width = 180
height = 120
input.i1 = { once = 0 }
input.i2 = { once = 1 }

[[process]]
source = "context://stdio/stdout"
x = 300.9684
y = 101.93169
width = 180
height = 120

[[connection]]
from = "add"
to = "add/i2"

[[connection]]
name = "next value"
from = "add"
to = "stdout"

[[connection]]
name = "previous"
from = "add/i2"
to = "add/i1"
