flow = "even"

[[process]]
alias = "args"
source = "lib://flowruntime/args/get"

[[process]]
alias = "to_number"
source = "lib://flowstdlib/fmt/to_number"

[[connection]]
from = "args/1"
to = "to_number"

[[process]]
source = "remainder_zero"
input.divisor = { always =  2 }

[[connection]]
from = "to_number"
to = "remainder_zero/dividend"

[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"

[[connection]]
from = "remainder_zero/has_zero_remainder"
to = "print"
