flow = "all_numbers"

# Generate the range of numbers from 1..20
[[process]]
alias = "numbers"
source = "lib://flowstdlib/math/sequence"
input.start = {once =  1}
input.step = {once =  1}
input.end = {once =  20}

[[process]]
alias = "array"
source = "lib://flowstdlib/data/accumulate"
input.chunk_size = {always =  20}
input.partial = {once =  []}

[[connection]]
from = "numbers/sequence"
to = "array/values"

[[connection]]
from = "array/partial"
to = "array/partial"

####### Output
[[process]]
alias = "print"
source = "lib://flowruntime/stdio/stdout"

[[connection]]
from = "array/chunk"
to = "print"

