flow = "sequence"
docs = "DESCRIPTION.md"

[[process]]
source = "lib://flowstdlib/math/sequence"
input.start = {once =  2}
input.step = {once =  3}
input.limit = {once =  100}

[[process]]
source = "context://stdio/stdout"

[[connection]]
from = "sequence/number"
to = "stdout"

# Output a string to show we're done when the Sequence ends
[[process]]
source = "lib://flowstdlib/control/join"
input.data = {once =  "Sequence done"}

# Trigger the output of the "Sequence done" string when the sequence sub-flow outputs a value
#on the "last" output
[[connection]]
from = "sequence/last"
to = "join/control"

# Send the string passed when the last number is output to stdout also
[[connection]]
from = "join"
to = "stdout"