[package]
name = "divide"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "divide"
crate-type = ["cdylib"]
path = "divide.rs"
rustflags = ["-C", "link-arg=--gc-targets"]

[dependencies]
flowcore = { workspace = true }
flowmacro = { workspace = true }
serde_json = { workspace = true, default-features = false }