function = "divide"
description = "Divide one input by another, producing outputs for the dividend, divisor, result and the remainder "
source = "divide.rs"
docs = "divide.md"
type = "rust"

[[input]]
name = "dividend" # - the number to be divided, of type `Number`
type = "number"

[[input]]
name = "divisor" # - the number to divide by, of type `Number`
type = "number"

[[output]]
name = "result" # - the result of the division, of type `Number`
type = "number"

[[output]]
name = "remainder" # - the remainder of the division, of type `Number`
type = "number"