function = "multiply_row"
source = "multiply_row.rs"
docs = "multiply_row.md"
type = "rust"

[[input]]
name = "a"
type = "array/number"

[[input]]
name = "b"
type = "array/number"

[[output]]
type = "number"