function = "multiply_row"
source = "multiply_row.rs"
docs = "multiply_row.md"
type = "rust"

[[input]]
name = "a"
type = "array/number"

[[input]]
name = "b"
type = "array/number"

[[output]]
name = "product"
type = "number"

[[output]]
name = "a_index"
type = "number"

[[output]]
name = "b_index"
type = "number"