flow = "double-connection"

[[process]]
source = "context://args/get"

[[process]]
source = "context://stdio/stdout"

[[connection]]
from = "get/string/1"
to = "stdout"

[[connection]]
from = "get/string/3"
to = "stdout"