function = "index"
source = "index.rs"
docs = "index.md"
type = "rust"

[[input]]
name = "value" # - the stream of input values to select from

[[input]]
name = "previous_value" # - the loop-backed previous value to enable selecting "last"

[[input]]
name = "previous_index" # - the loop-backed previous index to enable counting
type = "number"

[[input]]
name = "select_index" # th index to select from, where -1 = "last"
type = "number"

[[output]]
name = "index" # the index of the value just processed and output on "value"
type = "number"

[[output]]
name = "value" # the value just processed

[[output]]
name = "selected_value" # the value selected by index - only output when selected