name = "render_pixel"

[[input]]
name = "bounds"

[[input]]
name = "x"
type = "Number"

[[input]]
name = "y"
type = "Number"

[[input]]
name = "upper_left"
type = "Json"

[[input]]
name = "lower_right"
type = "Json"

[[output]]
name = "value"

[[function]]
alias = "pixel_to_point"
source = "./src/pixel_to_point.toml"

[[function]]
alias = "escapes"
source = "./src/escapes.toml"

[[value]]
name = "limit"
type = "Number"
constant = 255

[[connection]]
from = "input/bounds"
to = "function/pixel_to_point/bounds"

[[connection]]
from = "input/x"
to = "function/pixel_to_point/x"

[[connection]]
from = "input/y"
to = "function/pixel_to_point/y"

[[connection]]
from = "input/upper_left"
to = "function/pixel_to_point/upper_left"

[[connection]]
from = "input/lower_right"
to = "function/pixel_to_point/lower_right"

[[connection]]
from = "function/pixel_to_point/"
to = "function/escapes/point"

[[connection]]
from = "value/limit"
to = "function/escapes/limit"

[[function]]
alias = "subtract"
source = "lib://flowstdlib/math/subtract.toml"

[[connection]]
from = "value/limit"
to = "function/subtract/i1"

[[connection]]
from = "function/escapes"
to = "function/subtract/i2"

[[connection]]
from = "function/subtract"
to = "output/value"