name = "render_a_row"

[[input]]
name = "row_bounds"

[[input]]
name = "upper_left"

[[input]]
name = "row_index"
type = "Number"

[[input]]
name = "lower_right"

[[output]]
name = "bytes"


# Column Generator to generate a series of column numbers to render each pixel in the row
[[value]]
name = "column_0"
type = "Number"
initial = 0

[[flow]]
alias = "column_range"
source = "../range/range.toml"

[[connection]]
from = "value/column_0"
to = "flow/column_range/start"

[[connection]]
from = "input/row_bounds/0"  # x or row width
to = "flow/column_range/limit"


# A store for the row_index that is read for each pixel
[[value]]
name = "row_index"
type = "Number"

[[connection]]
from = "input/row_index"
to = "value/row_index"

[[connection]] # a hack to refresh with the same number always
from = "value/row_index"
to = "value/row_index"


# Render a pixel
[[flow]]
alias = "render_pixel"
source = "render_pixel.toml"

[[connection]]
from = "flow/column_range/series"
to = "flow/render_pixel/x"

[[connection]]
from = "value/row_index"
to = "flow/render_pixel/y"

# TODO ADM will need to refresh these values for each column/pixel as otherwise will be exhausted on first pixel????
[[connection]]
from = "input/row_bounds"
to = "flow/render_pixel/bounds"

[[connection]]
from = "input/upper_left"
to = "flow/render_pixel/upper_left"

[[connection]]
from = "input/lower_right"
to = "flow/render_pixel/lower_right"

[[connection]]
from = "flow/render_pixel/value"
to = "output/bytes"