[workspace]
members = ["compare_switch", "index", "join", "route", "select", "tap"]
default-members = []

[workspace.package]
name = "control"
description = "The standard library of functions and flows for 'flow' programs"
version = "0.70.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/flow/README.md"
homepage = "http://andrewdavidmackenzie.github.io/flow/"
repository = "https://github.com/andrewdavidmackenzie/flow/"
readme = "README.md"
edition = "2021"

[profile.dev]
split-debuginfo = "unpacked"

