[package]
name = "route"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "route"
crate-type = ["cdylib"]
path = "route.rs"
rustflags = ["-C", "link-arg=--gc-targets"]

[dependencies]
flowcore = { workspace = true }
flowmacro = { workspace = true }
serde_json = { workspace = true, default-features = false }