function = "route"
source = "route.rs"
docs = "route.md"
type = "rust"

[[input]]
name = "data" # - the data flow we wish to control the flow if

[[input]]
name = "control" # - a boolean value to determine which output roue `data` is passed to
type = "boolean"

[[output]]
name = "true" # `if `control` is true `data` is routed here

[[output]]
name = "false" # if `control` is false `data` is routed here