flow = "mandlebrot"
docs = "DESCRIPTION.md"

[[process]]
source = "parse_args"

[[process]]
source = "generate_pixels"

# Connect size to pixel generator
[[connection]]
from = "parse_args/size"
to = "generate_pixels/size"

[[process]]
source = "render"

# Connections to render
[[connection]]
from = "parse_args/filename"
to = "render/filename"

[[connection]]
from = "parse_args/size"
to = "render/size"

[[connection]]
from = "parse_args/bounds"
to = "render/bounds"

# Connect pixel generator to render
[[connection]]
from = "generate_pixels/pixels"
to = "render/pixel"


