flow = "range-of-ranges"

[[process]]
alias = "limit-sequence"
source = "lib://flowstdlib/math/sequence"
input.start = {once = 1}
input.end = {once = 9}

# Generate a sequence of numbers from 0 upto the value from sequence above
[[process]]
alias = "second-sequence"
source = "lib://flowstdlib/math/sequence"
input.start = {constant = 0}

[[connection]]
from = "process/limit-sequence/sequence"
to = "process/second-sequence/end"

[[process]]
alias = "print"
source = "lib://runtime/stdio/stdout"

[[connection]]
from = "process/second-sequence/sequence"
to = "process/print"